name: CI

on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to develop
      run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff master -m "Merge branch 'master' into develop"
          git push
