name: Automerge

on:
  push:
    branches: [master]

jobs:

  merge:
    continue-on-error: true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          
    - name: Merge master back to develop
      run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff master -m "Merge branch 'master' into develop"
          git push
          
  create_pull_request:
    needs: merge
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "develop"
        pr_title: "Pulling master into develop"
        pr_label: "auto-merge-pr"
        github_token: ${{ secrets.GITHUB_TOKEN }}
